# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='logo',
            field=models.ImageField(default='/static/festivals/images/leeg.png', upload_to='uploads/'),
        ),
    ]
