# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_festival_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='festival',
            name='logo',
            field=models.ImageField(default='/uploads/leeg.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='festivalday',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='festivals.Festival'),
        ),
    ]
