# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_auto_20160402_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.Artist')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.Festival')),
            ],
        ),
        migrations.RemoveField(
            model_name='festivalday',
            name='festival',
        ),
        migrations.DeleteModel(
            name='FestivalDay',
        ),
        migrations.AddField(
            model_name='festival',
            name='performers',
            field=models.ManyToManyField(through='festivals.Performance', to='festivals.Artist'),
        ),
    ]
